"""fhir-sdc: Composable library and CLI for building FHIR SDC Questionnaires."""

from sdc.composition import (
    Composition,
    CompositionSection,
    Narrative,
    TEMPLATE_EXTRACT_CONTEXT_URL,
    TEMPLATE_EXTRACT_PROFILE,
    TEMPLATE_EXTRACT_URL,
    section,
)
from sdc.fhirpath import (
    answer_value,
    coding,
    ctx_where,
    item_path,
    nested_answer_value,
    placeholder,
    res_context,
    res_where,
)
from sdc.models import (
    EnableWhen,
    EnableWhenOperator,
    Extension,
    FhirVersion,
    Meta,
    PublicationStatus,
    Questionnaire,
    QuestionnaireItem,
    QuestionnaireItemType,
    SDC_URLS,
    resolve_fhir_version,
    set_fhir_version,
)
from sdc.transforms import (
    add_answer_option,
    add_enable_when,
    add_extension,
    add_item,
    add_template_extract,
    add_translation,
    extract_texts,
    find_item,
    remove_extension,
    remove_item,
    set_answer_value_set,
    set_enable_behavior,
    set_meta,
    validate,
)

__all__ = [
    # Composition models
    "Composition",
    "CompositionSection",
    "Narrative",
    "TEMPLATE_EXTRACT_CONTEXT_URL",
    "TEMPLATE_EXTRACT_PROFILE",
    "TEMPLATE_EXTRACT_URL",
    "section",
    # FHIRPath helpers
    "answer_value",
    "coding",
    "ctx_where",
    "item_path",
    "nested_answer_value",
    "placeholder",
    "res_context",
    "res_where",
    # Models
    "EnableWhen",
    "EnableWhenOperator",
    "Extension",
    "FhirVersion",
    "Meta",
    "PublicationStatus",
    "Questionnaire",
    "QuestionnaireItem",
    "QuestionnaireItemType",
    "SDC_URLS",
    "resolve_fhir_version",
    "set_fhir_version",
    # Transforms
    "add_answer_option",
    "add_enable_when",
    "add_extension",
    "add_item",
    "add_template_extract",
    "add_translation",
    "extract_texts",
    "find_item",
    "remove_extension",
    "remove_item",
    "set_answer_value_set",
    "set_enable_behavior",
    "set_meta",
    "validate",
]
